apiVersion: v1
kind: Pod
metadata:
  name: storage-pod

spec:
  containers:
    - name: app
      image: busybox:latest

      command:
        - sh
        - -c
        - |
          while true; do
            echo "Storage Pod is Running"
            sleep 10
          done
      
      volumeMounts:
        - name: app-storage
          mountPath: /data
  volumes:
    - name: app-storage
      persistentVolumeClaim:
        claimName: app-pvc
        
              